version: '3'
services:
  redis1:
    image: redis:latest
    ports:
      - "6381:6379"
  redis2:
    image: redis:latest
    ports:
      - "6382:6379"
  redis3:
    image: redis:latest
    ports:
      - "6383:6379"
