name: Build artifacts

on:
  push:
    tags:
      - '*'
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run tests
        run: |
          ./gradlew \
          :redpulsar-core:test \
          :redpulsar-jedis:test \
          :redpulsar-lettuce:test \
          -DexcludeTags="integration"
      - name: Build
        run: |
          ./gradlew \
          :redpulsar-core:build \
          :redpulsar-jedis:build \
          :redpulsar-lettuce:build \
          -x test
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: redpulsar-artifacts
          path: redpulsar*/build/libs/*.jar
