name: Build with Gradle

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Check formatting
        run: | 
          ./gradlew ktlintCheck
      - name: Archive linter report
        uses: actions/upload-artifact@v3
        with:
          name: ktlint-report
          path: build/reports/ktlint/**/*.txt
      - name: Run tests
        run: |
          ./gradlew test -DexcludeTags="integration"
      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/test-results/**/*.xml
